config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :update, :edit, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def edit
    render :edit
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to @board
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<%= form_for [@board] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h1>Click a Board To View Content</h1>
<%= link_to 'Create a New Board', new_board_path %>
<div>
<ul>
  <% @boards.each do |board| %>
    <li><%= link_to board.name, board %></li>
  <% end %>
</ul>
</div>

app/views/boards/new.html.erb
<%= form_for [@board] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
  <% end %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>
<hr />
<p>What would you like to do?</p>
<%# link_to 'View Topics', board_list_path(@board) %>
<br />
<%= link_to 'Edit Board', edit_board_path(@board) %>
<br />
<%= link_to 'Delete Board', @board, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>